provisionDataStore:
  cassandra: false
  elasticsearch: false
  kafka: false
storage:
  type: elasticsearch
  elasticsearch:
    usePassword: false
    host: elasticsearch-master.elasticsearch.svc.cluster.local