apiVersion: v1
kind: Pod
metadata:
  name: ubuntu
spec:
  containers:
    - name: ubuntu
      image: ubuntu_local:latest
      imagePullPolicy: IfNotPresent
      command: ["sh", "-c", "trap : TERM INT; sleep infinity & wait"]
      volumeMounts:
        - name: dockersock
          mountPath: "/var/run/docker.sock"
        - name: john
          mountPath: "/home/john"
  volumes:
    - name: dockersock
      hostPath:
        path: /var/run/docker.sock
    - name: john
      hostPath:
        path: /run/desktop/mnt/host/wsl/john
